PARTICIPANTS: use this file for creating the remove book from catalog diagram in mastery task 01
@startuml
actor Client
participant "RemoveBookFromCatalogActivity" as API
participant "CatalogDao" as CD
participant "CatalogItemVersion Table" as Table



    API -> CD: Check if book exists(bookId)
    CD --> API: BookNotFoundException
    API -> Client: BookNotFoundException
    deactivate API

    API -> CD: Check if book is active(bookId)
    CD --> API: BookNotFoundException
    API -> Client: BookNotFoundException
    deactivate API

    API -> CD: Deactivate book in table(bookId)
    activate CD
    CD -> Table: Update inactive=true for latest version of bookId
    Table --> CD: Update successful
    deactivate CD
    CD --> API: Success
    API -> Client: RemoveBookFromCatalogResponse {}
    deactivate API


@enduml